apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cosign-signing-key
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-rh1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        cosign.key: "{{ .cosign_key }}"
        password: "{{ .password }}"
  data:
    - secretKey: cosign_key
      remoteRef:
        key: rh1/platform/signing/cosign
        property: cosign_key
    - secretKey: password
      remoteRef:
        key: rh1/platform/signing/cosign
        property: password
