apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: galaxy-gpg-keyring
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-rh1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        pubring.kbx: "{{ .pubring_kbx }}"
        trusted.asc: "{{ .trusted_asc }}"
  data:
    - secretKey: pubring_kbx
      remoteRef:
        key: rh1/platform/signing/galaxy-gpg
        property: pubring_kbx
    - secretKey: trusted_asc
      remoteRef:
        key: rh1/platform/signing/galaxy-gpg
        property: trusted_asc
