apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ci-rh1-ee
resources:
- ci-rh1-ee-namespace.yml
- rh1-ee-repository.yml
- ee-minimal-rhel9-imagestream.yaml
- pipeline-serviceaccount.yml
- automationhub-credentials-externalsecret.yml
- quay-rh1-ee-robotaccount-externalsecret.yml
- cosign-signing-externalsecret.yml
- cosign-public-externalsecret.yml
- galaxy-gpg-keyring-externalsecret.yml