apiVersion: v1
imagePullSecrets:
- name: quay-rh1-ee-robotaccount
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: ee-builder-ci
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
secrets:
- name: quay-rh1-ee-robotaccount
- name: cosign-signing-key
- name: cosign-public-key
- name: galaxy-gpg-keyring