apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: rh1-ee
spec:
  url: "https://github.com/djdanielsson/rh1-ee"
  settings:
    pipelinerun_provenance: default_branch
  params:
    - name: ansible_galaxy_server_list
      value: "published,validated,certified,community"
    - name: ansible_galaxy_server_published_url
      value: "https://aap-dev-aap-dev.apps.cluster-96rm2.96rm2.sandbox766.opentlc.com/api/galaxy/content/published/"
    - name: ansible_galaxy_server_published_token
      secret_ref:
        name: automationhub-credentials
        key: token
    - name: ansible_galaxy_server_validated_url
      value: "https://aap-dev-aap-dev.apps.cluster-96rm2.96rm2.sandbox766.opentlc.com/api/galaxy/content/validated/"
    - name: ansible_galaxy_server_validated_token
      secret_ref:
        name: automationhub-credentials
        key: token
    - name: ansible_galaxy_server_certified_url
      value: "https://aap-dev-aap-dev.apps.cluster-96rm2.96rm2.sandbox766.opentlc.com/api/galaxy/content/rh-certified/"
    - name: ansible_galaxy_server_certified_token
      secret_ref:
        name: automationhub-credentials
        key: token
    - name: ansible_galaxy_server_community_url
      value: "https://aap-dev-aap-dev.apps.cluster-96rm2.96rm2.sandbox766.opentlc.com/api/galaxy/content/community/"
    - name: ansible_galaxy_server_community_token
      secret_ref:
        name: automationhub-credentials
        key: token