apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hub-collection-signing-key
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-rh1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        collection_signing.key: "{{ .private_key }}"
        collection_signing.pub: "{{ .public_key }}"
  data:
    - secretKey: private_key
      remoteRef:
        key: rh1/platform/signing/hub-collection
        property: private_key
    - secretKey: public_key
      remoteRef:
        key: rh1/platform/signing/hub-collection
        property: public_key
