apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aap-admin-password
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-rh1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: rh1/platform/aap/dev/admin-password
        property: password
