apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cosign-public-key
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-rh1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        cosign.pub: "{{ .cosign_pub }}"
  data:
    - secretKey: cosign_pub
      remoteRef:
        key: rh1/platform/signing/cosign
        property: cosign_pub
