apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: ci-rh1-release-manifest
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
secrets:
- name: git-credentials