apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: aap
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  targetNamespaces:
    - ci-rh1-aap-config-as-code #todo make patch