apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ci-rh1-aap-config-as-code
resources:
- ci-rh1-aap-config-as-code-namespace.yml
- rh1-aap-config-as-code-repository.yml
- aap-operatorgroup.yml
- aap-subscription.yml
- pipeline-serviceaccount.yml
- quay-rh1-ee-robotaccount-externalsecret.yml