apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quay-rh1-ee-robotaccount
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: quay-rh1-ee-robotaccount
        metadataPolicy: None
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-rh1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        .dockerconfigjson: "{{ .dockerconfigjson_b64 | b64dec }}"
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson