apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: rh1-cluster-config
spec:
  url: "https://github.com/djdanielsson/rh1-cluster-config"
  settings:
    pipelinerun_provenance: default_branch
