apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quay-rh1-ee-robotaccount
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: quay-rh1-ee-robotaccount
      metadataPolicy: None
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-rh1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain