apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  name: galaxy-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-rh1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: rh1/platform/ci/automationhub
        property: token
    - secretKey: server
      remoteRef:
        key: rh1/platform/ci/automationhub
        property: server
