apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ci-rh1-custom-collection
resources:
- ci-rh1-custom-collection-namespace.yml
- rh1-custom-collection-repository.yml
- galaxy-credentials-externalsecret.yaml