apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
secrets:
- name: galaxy-credentials
- name: cosign-signing-key
- name: cosign-public-key
- name: galaxy-gpg-keyring
